Week12
rebs1203/06-jobs-api pull request #3
Opened 2024-01-08 22:28 UTC by rebs1203

I followed the lesson and changed everything according to my own project, however when trying to view my page on localhost I get an authentication error which does not make it possible for me to view my project or test it. What is it that is wrong? Maybe I missed something when changing the information of the code, maybe a typo?

2024-01-17 13:51 UTC, joseluiz requested changes
Hi @rebs1203, 

I noticed some issues in your code while reviewing your PR. Please check your PR comments for more information. I noticed that you are using the "jobs" fields instead of the "groceries" fields, but your API is for managing groceries, not jobs.

Please review the "delete groceries" functionality, as it doesn't seem to be working. Additionally, the cancel button and adding/editing a grocery is also not functioning properly.

If you have any questions, feel free to contact me on Slack.

2024-01-17 13:51 UTC, joseluiz commented on public/addEdit.js
> +import { showGroceries } from "./groceries";
There is an error here, it should be "./groceries.js"

2024-01-17 13:51 UTC, joseluiz commented on public/delete.js
> +import { showGroceries } from "./groceries";
There is an error here, it should be "./groceries.js"

2024-01-17 13:51 UTC, joseluiz commented on public/login.js
> +  import { showGroceries } from "./groceries";
There is an error here, it should be "./groceries.js"

2024-01-17 13:51 UTC, joseluiz commented on public/groceries.js
> +          for (let i = 0; i < data.jobs.length; i++) {
There is an error here; it should be data.products.length because the groceries endpoint is returning products, not jobs.

2024-01-17 13:51 UTC, joseluiz commented on public/index.html
Hey, @rebs1203, please update all fields to be compatible with your grocery management API. All fields here are for the Job, but your API is for managing groceries, not jobs.

2024-01-17 13:51 UTC, joseluiz commented on public/addEdit.js
> +            if (addingJob.textContent === "update") {
There is an error here, it should be addingProduct.

2024-01-17 13:51 UTC, joseluiz commented on public/groceries.js
> +            let editButton = `<td><button type="button" class="editButton" data-id=${data.groceries[i]._id}>edit</button></td>`;
There are errors here; change 'data.groceries' for 'data.products'.

2024-01-17 13:51 UTC, joseluiz commented on public/addEdit.js
> +          status.value = data.groceries.status;
There are errors here, change 'data.groceries' for 'data.product'.

2024-01-22 13:01 UTC, joseluiz requested changes
Hey @rebs1203, please review your PR comments, there are additional fixes you need to solve. If you have any questions, feel free to call me on Slack.

2024-01-22 13:01 UTC, joseluiz commented on public/index.html
> +          <label for="addedby">added by:</label>
You can remove this field from the form because it is added by the logged-in user in the back end.

2024-01-22 13:01 UTC, joseluiz commented on public/index.html
> +          <input type="text" id="name" />
Change the ID for "productName" because it conflicts with the user name.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +  name = document.getElementById("name");
As mentioned in the index.html file, you also need to change the ID for "productName" instead of "name" here.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +          name.value = data.groceries.name;
You need to replace data.groceries with data.product as the API is returning product, not groceries. Replace it in all instances where data.groceries are used.

2024-01-22 13:01 UTC, joseluiz commented on public/groceries.js
> +            let editButton = `<td><button type="button" class="editButton" data-id=${data.groceries[i]._id}>edit</button></td>`;
You need to replace data.groceries with data.products as the API is returning products, not groceries. Replace it in all instances where data.groceries are used.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +  createdBy = document.getElementById("addedby");
You can remove it because the addedBy field is automatically added by the backend with the user logged-in.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +                  createdBy: createdBy.value,
You can remove it because the addedBy field is automatically added by the backend with the user logged-in.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +                createdBy.value = "";
You can remove it because the addedBy field is automatically added by the backend with the user logged-in.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +      createdBy.value = "";
You can remove it because the addedBy field is automatically added by the backend with the user logged-in.

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +          status.value = data.groceries.status;
You can remove it because the addedBy field is automatically added by the backend with the user logged-in.

2024-01-22 13:01 UTC, joseluiz commented on controllers/groceries.js
> +    res.status(StatusCodes.OK)
You need to call res.json, otherwise the backend will not return any result.
Ex:
res.status(StatusCodes.OK).json(`Product with id ${productId} was successfully deleted.`)

2024-01-22 13:01 UTC, joseluiz commented on public/delete.js
The delete function needs to be fixed. There is a lot of unnecessary code. Here is an example of how the delete function should be:

import { showGroceries } from "./groceries.js";
import {
  message,
  token,
} from "./index.js";

export const handleDelete = async (productId) => {
              let url = `/api/v1/groceries/${productId}`;
            
              try {
                const response = await fetch(url, {
                  method: "DELETE",
                  headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${token}`,
                  }
                });
            
                const data = await response.json();
                if (response.status == 200) {
                    message.textContent = "The product was successfully deleted."; 
                    showGroceries();
                } else {
                    message.textContent = data.msg;
                }
              } catch (err) {
                console.log(err);
                message.textContent = "A communication error occurred.";
              }
  };

2024-01-22 13:01 UTC, joseluiz commented on public/groceries.js
> +          }
You need to add this code for the delete function to work.

`else if (e.target.classList.contains("deleteButton")) {
            message.textContent = "";
            handleDelete(e.target.dataset.id);
          }`

2024-01-22 13:01 UTC, joseluiz commented on public/groceries.js
> +  import { showAddEdit } from "./addEdit.js";
Import the handleDelete function here.

import { handleDelete } from "./delete.js";

2024-01-22 13:01 UTC, joseluiz commented on public/addEdit.js
> +          }
The cancel function is not working when adding or editing a grocery. Add this code to fix it.

`else if(e.target == editCancel) {
            message.textContent = "";
            showGroceries();
          }`

2024-01-23 12:58 UTC, joseluiz requested changes
@rebs1203 There are still three things that need fixing in your work. Please take a look at my PR comments for more details. You're almost there. ;)

2024-01-23 12:58 UTC, joseluiz commented on public/addEdit.js
> +          name.value = data.products.name;
Change `data.products` for `data.product`.

2024-01-23 12:58 UTC, joseluiz commented on public/index.html
> +            <option value="notfound">not found</option>
Change `notfound` for `not found`, because in you model it expected to receive `not found`.

2024-01-23 12:58 UTC, joseluiz commented on public/addEdit.js
> +          }
@rebs1203 You forgot to fix this issue.

2024-01-23 19:53 UTC, rebs1203 commented on public/addEdit.js
> +          }
Sorry about that, I thought I did. Where exactly is the else if supposed to go?

2024-01-23 21:56 UTC, joseluiz commented on public/addEdit.js
> +          }
It should go on line 67 where you close this if `if (e.target === addingProduct) {`.

2024-01-25 12:15 UTC, joseluiz approved these changes
Hi @rebs1203. It looks good now. I'm approving your PR, you can merge it. Congratulation!

2024-01-25 22:03 UTC, closed without merging